site_name: Wordpress Plugin - Entry List
repo_url: https://github.com/RcArtSolutions/wp-entry-list
repo_name: GitHub
site_author: Elias Ruemmler
docs_dir: null

pages:
- 'Einführung': 'README.md'
- 'Benutzung': 'docs/user-guide.md'
- 'Über': 'docs/about.md'
