site_name: Wordpress Plugin - Entry List
repo_url: https://github.com/RcArtSolutions/wp-entry-list
repo_name: GitHub
site_author: Elias Ruemmler

pages:
- 'Einführung': 'README.md'
- 'Benutzung': 'user-guide.md'
- 'Über': 'about.md'
